# Generated by Django 4.1.5 on 2023-02-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
